### ISSUE TITLE
Support PNG Sequence - additional if possible

### ISSUE THREAD

**Issue by SyDant** [anosu/Spine-Viewer-Vue#7]
应用程序很好，请问能否添加一些新功能？比如
- Support PNG Transparent Sequence 
- Ability to Add Background Image from file
- 能够更改所有的秒数（例如在这个图中，应用程序识别出有4秒，能否更改它？)
![image](https://github.com/user-attachments/assets/dc17221a-0b34-4014-937c-0e9966c1bcb3)

谢谢！

**Comment by anosu** [comment]
You can load background image by "设置背景" and remove it by "移除背景".
Hover on button or text to get english description. I'm sorry for my poor ability to add support for multi language.
You can move or zoom it when pressing CTRL. But I'm not sure if there is any bug in this feature.

👌I've added PNG Sequence option.

What does it mean to change total seconds?
更改所有的秒数是什么意思？

**Comment by SyDant** [comment]
What does it mean to change total seconds?
更改所有的秒数是什么意思

就像是改变每秒的时间，比如在动画标签中打开一个spine时显示为4秒，那么是否可以整体改变这个秒数？这样在导出.mp4时可以变成10秒等等。

**Comment by SyDant** [comment]
Can I contribute regarding multi-language support? If so, where should I start? Will you provide a draft in the form of images, and then you will change the UI ?

**Comment by anosu** [comment]
> Can I contribute regarding multi-language support? If so, where should I start? Will you provide a draft in the form of images, and then you will change the UI ?

Maybe I dont have much time to do it.

**Comment by anosu** [comment]
> What does it mean to change total seconds? 更改所有的秒数是什么意思
> 
> 就像是改变每秒的时间，比如在动画标签中打开一个spine时显示为4秒，那么是否可以整体改变这个秒数？这样在导出.mp4时可以变成10秒等等。
> 
> "Like changing the time per second, for example, when opening a spine in the animation tab it appears as 4 seconds, can that duration be changed overall? So later when exporting to .mp4, it could become 10 seconds and so on."

decrease/increase the speed of animation? Or decrease/increase the speed of each individual animation?

**Comment by SyDant** [comment]
decrease/increase the speed of animation, not each individual
im notice this 
![image](https://github.com/user-attachments/assets/a2699b0b-8d63-4687-ada9-eef4da50c0ed)
if I change it like making the speed 2.00x or mixing 2.0s. when exporting to .gif / .mp4 will it have an effect?

**Comment by anosu** [comment]
Yes. What you see is what you get in most cases.

**Comment by SyDant** [comment]
okay thanks you
